frontend/db.json
frontend/package-lock.json
frontend/package.json

ran npm start in terminal in frontend folder

Installed concurrently as a dependency.

---

frontend/src/app/uploading/uploading.component.css
frontend/src/app/uploading/uploading.component.html
frontend/src/app/uploading/uploading.component.ts

No functionality was changed, simply style changes to align the Uploading section more closely with the rest of the project.
NA

SPJP-107 - Stylistic changes

---

package-lock.json

https://unf-sp.atlassian.net/browse/SPJP-110
Updates npm packages to reduce security issues. However, one issue still exists...
> xlsx  *
> Severity: high
> Prototype Pollution in sheetJS - https://github.com/advisories/GHSA-4r6h-8v6p-xvw6
> SheetJS Regular Expression Denial of Service (ReDoS) - https://github.com/advisories/GHSA-5pgg-2g8v-p4x9
> No fix available
> node_modules/xlsx

[SPJP-110] Update npm packages (Jan 2025)

---

frontend/src/app/reporting/reporting.component.css
frontend/src/app/reporting/reporting.component.html
frontend/src/app/reporting/reporting.component.ts
frontend/src/app/services/cases.service.ts
frontend/src/app/services/firebaseConnection.ts

https://unf-sp.atlassian.net/browse/SPJP-104
https://unf-sp.atlassian.net/browse/SPJP-117
1. Users can now go back and x time periods on reports
2. Data shows as expected (without filtered to 2024) and added a firestore index to prevent a 400 response
3. Reports now filter out deleted cases
- Test that cases show in the cases tab 
- Test that reports are not empty for various time periods (may need to go back some periods since we haven't added some in a while)

[SPJP-104] Report should filter out deleted cases

---

frontend/src/app/app.routes.ts
frontend/src/app/guards/no-auth.guard.ts
frontend/src/app/services/auth.service.ts
frontend/src/app/services/firebaseConnection.ts
frontend/src/app/view/staff-login/staff-login.component.ts

I fixed the bug that redirected to the cases page on reloads from the reports page as an admin. I also fixed the redirects to the respective page after logins.

SPJP 119 fixed reports refresh bug & redirects after login

---

frontend/src/app/sidebar/sidebar.component.html

added logout button

---

frontend/src/app/sidebar/sidebar.component.html

FIxed user list styling

---

frontend/src/app/uploading/uploading.component.ts

Small change to reference central location for status and species list.
Saw change in localhost.

Changed static Status and Species list to reference cental location. (small change)

---

frontend/src/index.html
package-lock.json
package.json

https://unf-sp.atlassian.net/browse/SPJP-134
Updates packages to improve security and rename default page title 
Ran the project locally to ensure it builds

[SPJP-134] Update packages to address Github security issues v2

---

frontend/src/app/uploading/uploading.component.ts

Simple change that sends a toast notification that alerts the user that files that were of the incorrect file type were discarded.
Tried uploading a file with a .png type.

Added an informational toast for incorrect file formats. (simple change)

---

frontend/src/app/models/case.ts
frontend/src/app/services/firebaseConnection.ts
frontend/src/app/uploading/uploading.component.ts

Gets the Timestamp from the read XLSX file and converts it to a Timestamp, applied to the Case.
Case interface now has updateDate (in case it becomes something to be used) and callDate.
Uploads now add the callDate Timestamp property when uploaded.
I also updated the comment doc in the Case interface to reflect changes (non-breaking change)
Printed to console and checked output.

First iteration of adding a Timestamp to the cases based on callDate.

---

frontend/src/app/services/auth.service.ts
frontend/src/app/services/firebaseConnection.ts
frontend/src/app/sidebar/sidebar.component.css
frontend/src/app/sidebar/sidebar.component.html
frontend/src/app/sidebar/sidebar.component.ts
package-lock.json

Added a minor addition where users can click on their names to access their profile.

added link to logged in user name

---

frontend/src/app/admin-acct-profile/admin-profile-view.component.html
frontend/src/app/admin-acct-profile/admin-profile-view.component.ts
frontend/src/app/services/auth.service.ts
frontend/src/app/services/firebaseConnection.ts

I completed user deactivations and activations and added toastr notifs instead of alerts

added toastr notifs and user activations

---

package-lock.json

Minor dependency issue is fixed. Include the motivation and context, and list any dependencies that are required for this change.

fix dependency issues

---

angular.json
frontend/src/app/accountProfile/account-profile.component.html
frontend/src/app/accountProfile/account-profile.component.ts
frontend/src/app/app.config.ts
frontend/src/app/services/firebaseConnection.ts
frontend/src/app/sidebar/sidebar.component.html
frontend/src/app/view/change-password/change-pswd-dialog.component.html
frontend/src/app/view/change-password/change-pswd-dialog.component.spec.ts
frontend/src/app/view/change-password/change-pswd-dialog.component.ts
frontend/src/app/view/usersList/users-list.component.html
frontend/src/index.html
frontend/src/styles.css
package-lock.json
package.json

Here I completed the change password functionality and added user role to users lists as per Lauren's request
I also used angular material for the dialog window to change password. To install it in your environment, use the command `ng add @angular/material` and use the cyan theme, no topgraphy changes, and yes to animations.
- [] This change requires a documentation update

completed pswd updates and added role to user list

---

frontend/src/app/reporting/reporting.component.ts

https://unf-sp.atlassian.net/browse/SPJP-132
- Default to monthly timeframe and reorder array to prevent ui not in sync with the data displaying 

[SPJP-132] All timeframes filter doesn't show all data on first load

---

frontend/src/app/admin-dash/admin-dashboard.component.html
frontend/src/app/app.routes.ts
frontend/src/app/view/usersList/users-list.component.css
frontend/src/app/view/usersList/users-list.component.html

styling changes

---

frontend/src/app/services/firebaseConnection.ts

Updated logic for password reset

password reset update

---

apphosting.yaml

https://unf-sp.atlassian.net/browse/SPJP-150
- Decreased min instances for cloud hosting
- I manually change this on each release, it's a bit slow but it's better costs wise

[SPJP-150] Decrease default cloud run min instances 

---

frontend/src/app/accountProfile/account-profile.component.ts
frontend/src/app/services/firebaseConnection.ts

fixed account profile reload  & login validation bug

---

frontend/src/app/uploading/uploading.component.ts

Altered Excel read function to group messages by message number, making it more robust to incorrectly ordered rows.
Tested by putting arbitrary numbers for message numbers (in pairs) and checking that the edit data table shows all new cases.

Group messages from excel file to increase robustness of code.

---

backend/src/index.js
frontend/src/app/services/firebaseConnection.ts

I updated the backend URL for API calls to `https://jax-humane-pet-center-system.onrender.com`, which is currently hosting the backend server. Looking to migrate to cloud functions before or after the project handoff.

updated backend url

---

frontend/src/app/services/firebaseConnection.ts

acct creation hotfix

---

frontend/src/app/uploading/uploading.component.css
frontend/src/app/uploading/uploading.component.html
frontend/src/app/uploading/uploading.component.ts

Changed Edit and Remove File buttons and replaced with the same icons used in Case Management section page for consistency.
Also added a hint in the Message/Note section of the editing uploaded case window to help users view the full note info more easily. -Cleaned up some random comments/unused commented code.
Might make more minor changes to cleanup how the Apply Changes button behaves (if resizing the window smaller, the page goes up behind the button and the button starts floating beyond the window). Might also change the border around the Edit and Remove File icons to a changed background color, depends on which looks better overall. Or nothing.
Added title properties to icons to give hints to their purpose in life.
Tested functionality of the icons after changing the buttons to …

Minor visual changes to uploading page (icons)

---

frontend/src/app/constants.ts
frontend/src/app/uploading/uploading.component.css
frontend/src/app/uploading/uploading.component.html
frontend/src/app/uploading/uploading.component.ts
frontend/src/styles.css

Changed how the XLSX file is read and parsed and now is cleaner and more robust.
This PR also includes some input validation for the phone number field, requiring either a complete and properly formatted phone number or no number at all. Upload will be restricted until this is met.
Incorrect phone numbers are bordered in red so it is easier to find.
The # of Pets column also does this if the number is over 99, though it does not restrict uploading.
The callDate property of the cases generated from the Excel file are pulled from the data or are the upload date if no date can be parsed.
I tried uploading the entirety of the VM log and accounting for each error along the way.
I also tried putting incorrectly formatted phone numbers and pet #s in, as well as incorrectly formatted data in the …

Adjusted upload strategy
